#!/bin/sh -e

wine32=$HOME/.apt/usr/lib/wine-development/wine
wine64=/usr/lib/wine-development/wine64

wine32_hint () {
    echo "it looks like wine32-development is missing, you should install it."
    if [ "$(dpkg --print-architecture)" = "amd64" ] && ! dpkg --print-foreign-architectures | grep -qx "i386"; then
        echo "multiarch needs to be enabled first.  as root, please"
        echo "execute \"dpkg --add-architecture i386 && apt-get update &&"
        echo "apt-get install wine32-development\""
    else
        echo "as root, please execute \"apt-get install wine32-development\""
    fi
}

if test -x $wine32; then
    wine=$wine32
elif test -x $wine64; then
    wine=$wine64
    if test -z "$WINELOADER"; then
        export WINELOADER=$wine64
    fi
    case "x$WINEDEBUG" in
        x-all*|x*,-all*|x*err-all*)
            ;;
        *)
            wine32_hint >&2
            ;;
    esac
else
    echo "error: unable to find wine executable.  this shouldn't happen." >&2
    exit 1
fi

if test -z "$WINEDEBUG"; then
    export WINEDEBUG=fixme-all
fi

exec $wine "$@"
